### ISSUE TITLE
Order deny,allow

### ISSUE THREAD

**Issue by DanielWaltz** [phanan/htaccess#16]
First off, awesome snippet collection! Very useful.

One thing I want to note however is having a space between deny,allow or allow,deny will throw back a server error. The space in between those (deny, allow) should be removed (deny,allow).

Thanks.

**Comment by phanan** [comment]
Fixed, thanks. Apparently this only happens on certain versions of Apache.

**Comment by DanielWaltz** [comment]
That turnaround. Thank you sir!
