### ISSUE TITLE
cult host liberation

### ISSUE THREAD

**Issue by TameOfGroans** [phanan/htaccess#39]
Please consider adding some snippets for those not in the cult of www, but who would prefer to display domain uncluttered in URI. 

Plainly I am not advocating contrawwwism. 

[contratheism]

There is room for http://no-www.org and cultists alike. Evidently there is more space for the former as it consumes fewer bits.

**Comment by Chouchen** [comment]
Well, [there are some](https://github.com/phanan/htaccess/blob/master/README.md#force-non-www) 
There's even a link to http://no-www.org/ ...

**Comment by TameOfGroans** [comment]
Could this neutrality be proffered on the project description?

**Comment by Chouchen** [comment]
Well, it's true that, when I translated it, I found the introduction a bit too... personal. 
It'd be fine if it was but, now, this repo is followed by nearly 7k users.

I guess this sentence could be delete for clarity : 
> I decided to create this repo after getting so tired (and bored) with Googling everytime there's a need of forcing www for my new website.

What do you think :question:

**Comment by phanan** [comment]
:+1: I'll be on it when I get back to my desk. Or if you can submit a PR,
why not ;)

**Comment by phanan** [comment]
There you go.
