### ISSUE TITLE
Remove www with 2nd subdomain for https

### ISSUE THREAD

**Issue by brohiem** [phanan/htaccess#54]
Can't get this to handle the case when a user enters www and a subdomain over HTTPS.

NOT WORKING:
https://www.mysubdomain.mydomain.com --> https://mysubdomain.mydomain.com

WORKING:
http://www.mysubsomain.mydomain.com  --> https://mysubsomain.mydomain.com

**Comment by phanan** [comment]
What section? How about a PR if you could, too? :smile:
