### ISSUE TITLE
Recommendation to remove www is questionable

### ISSUE THREAD

**Issue by salcode** [phanan/htaccess#7]
I disagree with the line

> It's actually recommended to remove www from your domain. Surprise surprise!

at https://github.com/phanan/htaccess#force-non-www

While one might choose to omit the __www__ from a branding perspective, from a technical perspective it is generally preferable to redirect to the __www__ version of the site.

Related Articles
- http://www.yes-www.org/why-use-www/
- https://devcenter.heroku.com/articles/apex-domains
- http://serverfault.com/questions/145777/what-s-the-point-in-having-www-in-a-url

Overall, this is a great resource.  Thanks.

**Comment by pyrokinetiq** [comment]
I disagree wholeheartedly with the opinions presented in the linked articles; www. is redundant, if you have a high traffic site which may need to point to various servers to remain reliable, then your A, NS and SOA records should be pointing to a load balancer which then resolves to the desired location such as a CDN or your API server.

**Comment by phanan** [comment]
I'd agree to remove the recommendation to remove (no pun) www. The repo should be neutral -- guess https://github.com/phanan/htaccess/commit/809967e8dcbfca16e304f4e9fc3da2e1dc21ef98 should fix it.
