### ISSUE TITLE
Remove the includeSubDomains from Strict-Transport-Security

### ISSUE THREAD

**Issue by 2ndkauboy** [phanan/htaccess#87]
The optional `includeSubDomains` flag will enforce HTTPS on all subdomains. Any subdomain that will not have HTTPS will be blocked by the browser. Clearing the "cache" for HSTS is very complicated. As the `max-age` is set to one year, this can have a massive negative effect, if you, for whatever reason, need to have a subdomain on any server without HTTPS.

**Comment by phanan** [comment]
Good idea. Personally, I got into the trouble of forcing HSTS on subdomains, too, and yes, you can't really clear the "cache" because it's _built into_ the browser.

**Comment by 2ndkauboy** [comment]
It's possible to clear it (in Chrome using the hidden `chrome://net-internals/#hsts` settings). But for most users it's not really possible.

**Comment by phanan** [comment]
Indeed, I was mistakenly referring to the `preload` setting.

**Comment by inetbiz** [comment]
I would keep it as-is and add comment to remove `includeSubDomains` if they aren't going to use SSL everywhere. SSL everywhere is recommended best practices. I wrote about **HSTS** for GlobalSign, Inc. https://www.globalsign.com/en/blog/what-is-hsts-and-how-do-i-use-it/
